### ISSUE TITLE
Dataset for the model

### ISSUE THREAD

**Issue by sugandh-2791** [sauer3/crop-classification#1]
I could not find the link to the dataset that you used for the modeling. Could you please share the data? Thanks

**Comment by sauer3** [comment]
This was part of a Zindi coding challenge. The source data can be found here: https://zindi.africa/competitions/farm-pin-crop-detection-challenge/data

**Comment by rongtongxueya** [comment]
Is this linked dataset really downloadable? Why can't I download the data by clicking on the download address of this link? Can't download any folder?
