### ISSUE TITLE
data set

### ISSUE THREAD

**Issue by miao19980215** [sauer3/crop-classification#2]
Could you upload your dataset? thank you very much

**Comment by sauer3** [comment]
This was part of a Zindi coding challenge. The source data can be found here: https://zindi.africa/competitions/farm-pin-crop-detection-challenge/data

**Comment by rongtongxueya** [comment]
Is this linked dataset really downloadable? Why can't I download the data by clicking on the download address of this link? Can't download any folder?

**Comment by sauer3** [comment]
If you go to the link and scroll down to the bottom you will see options to
download the data.
